baseurl: ''
permalink: pretty
title: 'Candidatura UGT Vicom Bilbao'
languages: ["es", "eu"]
exclude_from_localizations: ["images", "css", "assets", "_sass"]

logo:
  mobile: "images/logo/logo.png"
  mobile_height: "32px"
  #mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  #desktop_width: "192px"

home: 
  limit_news: 6

collections:
  news:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-multiple-languages-plugin
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
